# URL-lister til partiprogram/politik-undersider per parti (bokstav som nøgle).
PARTY_MANIFESTS: dict[str, list[str]] = {
    'A': [  # Socialdemokratiet – https://www.socialdemokratiet.dk/det-vi-mener/
        'https://www.socialdemokratiet.dk/det-vi-mener/sundhed-og-psykiatri/',
        'https://www.socialdemokratiet.dk/det-vi-mener/forsvarspolitik/',
        'https://www.socialdemokratiet.dk/det-vi-mener/rigsfaellesskabet/',
        'https://www.socialdemokratiet.dk/det-vi-mener/indvandring/',
        'https://www.socialdemokratiet.dk/det-vi-mener/klima-og-energi/',
        'https://www.socialdemokratiet.dk/det-vi-mener/land-og-bydistrikter/',
        'https://www.socialdemokratiet.dk/det-vi-mener/finanspolitik/',
        'https://www.socialdemokratiet.dk/det-vi-mener/miljoe-og-landbrug/',
        'https://www.socialdemokratiet.dk/det-vi-mener/udenrigs-og-eu/',
        'https://www.socialdemokratiet.dk/det-vi-mener/aeldre/',
        'https://www.socialdemokratiet.dk/det-vi-mener/arbejdsmarked/',
        'https://www.socialdemokratiet.dk/det-vi-mener/retspolitik/',
        'https://www.socialdemokratiet.dk/det-vi-mener/skattepolitik/',
        'https://www.socialdemokratiet.dk/det-vi-mener/uddannelse/',
        'https://www.socialdemokratiet.dk/det-vi-mener/boligpolitik/',
        'https://www.socialdemokratiet.dk/det-vi-mener/kulturpolitik/',
        'https://www.socialdemokratiet.dk/det-vi-mener/transport/',
        'https://www.socialdemokratiet.dk/det-vi-mener/ervhervspolitik/',
        'https://www.socialdemokratiet.dk/det-vi-mener/socialpolitik/',
        'https://www.socialdemokratiet.dk/det-vi-mener/ligestilling/',
    ],
    'B': [  # Radikale Venstre – https://www.radikale.dk/politik/vi-mener/
        'https://www.radikale.dk/politik/vi-mener/udspil/',
        'https://www.radikale.dk/politik/vi-mener/oekonomi/',
        'https://www.radikale.dk/politik/vi-mener/udlaendinge/',
        'https://www.radikale.dk/politik/vi-mener/uddannelse/',
        'https://www.radikale.dk/politik/vi-mener/transport/',
        'https://www.radikale.dk/politik/vi-mener/sundhed-og-forebyggelse/',
        'https://www.radikale.dk/politik/vi-mener/skole/',
        'https://www.radikale.dk/politik/vi-mener/seniorer-og-aeldre/',
        'https://www.radikale.dk/politik/vi-mener/miljoe-og-natur/',
        'https://www.radikale.dk/politik/vi-mener/ligestilling/',
        'https://www.radikale.dk/politik/vi-mener/landbrug/',
        'https://www.radikale.dk/politik/vi-mener/landdistrikter/',
        'https://www.radikale.dk/politik/vi-mener/kultur/',
        'https://www.radikale.dk/politik/vi-mener/klima/',
        'https://www.radikale.dk/politik/vi-mener/kirke/',
        'https://www.radikale.dk/politik/vi-mener/europa-internationalt-samarbejde-og-sikkerhed/',
        'https://www.radikale.dk/politik/vi-mener/forskning/',
        'https://www.radikale.dk/politik/vi-mener/demokrati-og-retsstat/',
        'https://www.radikale.dk/politik/vi-mener/boern/',
        'https://www.radikale.dk/politik/vi-mener/boliger/',
    ],
    'C': [  # Det Konservative Folkeparti – https://konservative.dk/politik/
        'https://konservative.dk/politik/en-vaerdig-aeldrepleje/',
        'https://konservative.dk/politik/et-staerkt-forsvar/',
        'https://konservative.dk/politik/bandekriminalitet/',
        'https://konservative.dk/politik/beredskab/',
        'https://konservative.dk/politik/beskaeftigelse-og-pension/',
        'https://konservative.dk/politik/born-og-unge/',
        'https://konservative.dk/politik/civilsamfund-og-foreningsliv/',
        'https://konservative.dk/politik/energi/',
        'https://konservative.dk/politik/erhvervslivets-vilkar/',
        'https://konservative.dk/politik/et-sundhedsvaesen-for-alle/',
        'https://konservative.dk/politik/folkeskole-og-uddannelse/',
        'https://konservative.dk/politik/integration/',
        'https://konservative.dk/politik/klima/',
        'https://konservative.dk/politik/klimasikring/',
        'https://konservative.dk/politik/kunst-kultur-og-kirke/',
        'https://konservative.dk/politik/lov-og-orden/',
        'https://konservative.dk/politik/miljokriminalitet/',
        'https://konservative.dk/politik/mindre-bureaukrati/',
        'https://konservative.dk/politik/natur-og-biodiversitet/',
        'https://konservative.dk/politik/skatter-og-afgifter/',
        'https://konservative.dk/politik/statsborgerskab/',
    ],
    'F': [  # SF – https://sf.dk/det-vil-vi/
        'https://sf.dk/det-vil-vi/arbejdsmarkedspolitik/',
        'https://sf.dk/det-vil-vi/aeldrepleje/',
        'https://sf.dk/det-vil-vi/boern-og-unge/',
        'https://sf.dk/det-vil-vi/erhverv-og-teknologi/',
        'https://sf.dk/det-vil-vi/boligpolitik/',
        'https://sf.dk/det-vil-vi/eu-politik/',
        'https://sf.dk/det-vil-vi/handicap-og-inklusion/',
        'https://sf.dk/det-vil-vi/udenrigspolitik-og-forsvar/',
        'https://sf.dk/det-vil-vi/udviklingspolitik-og-international-solidaritet/',
        'https://sf.dk/det-vil-vi/klimapolitik-og-groenenergi/',
        'https://sf.dk/det-vil-vi/kultur-sport-medier/',
        'https://sf.dk/det-vil-vi/ligestilling/',
        'https://sf.dk/det-vil-vi/natur-miljoe-og-foedevarer/',
        'https://sf.dk/det-vil-vi/velfaerd-oekonomi-og-skat/',
        'https://sf.dk/det-vil-vi/religion-og-tro/',
        'https://sf.dk/det-vil-vi/retspolitik-og-sikkerhed/',
        'https://sf.dk/det-vil-vi/transport/',
        'https://sf.dk/det-vil-vi/sundhed/',
        'https://sf.dk/det-vil-vi/skole-uddannelse-forskning/',
        'https://sf.dk/det-vil-vi/ulighed-og-fattigdom/',
        'https://sf.dk/det-vil-vi/integration/',
    ],
    'H': [  # Borgernes Parti – https://borgernesparti.dk/vores-politik/
        'https://borgernesparti.dk/politik/magten-skal-tilbage-til-borgerne/',
        'https://borgernesparti.dk/politik/danmark-skal-ikke-foraeres-vaek-til-fremmede/',
        'https://borgernesparti.dk/politik/et-opgoer-med-klimahysteriet/',
        'https://borgernesparti.dk/politik/danmark-og-omverden/',
        'https://borgernesparti.dk/politik/dyrepolitik/',
        'https://borgernesparti.dk/politik/en-staerkere-familie/',
        'https://borgernesparti.dk/politik/erhvervspolitik/',
        'https://borgernesparti.dk/politik/et-groent-danmark/',
        'https://borgernesparti.dk/politik/forsvarspolitik/',
        'https://borgernesparti.dk/politik/frie-medier-for-alle/',
        'https://borgernesparti.dk/politik/handicappolitik/',
        'https://borgernesparti.dk/politik/landbrugspolitik/',
        'https://borgernesparti.dk/politik/seniorpolitik/',
        'https://borgernesparti.dk/politik/sundhedspolitik/',
        'https://borgernesparti.dk/politik/transportpolitik/',
    ],
    'I': [  # Liberal Alliance – https://www.liberalalliance.dk/politik/
        'https://www.liberalalliance.dk/politik/skat/',
        'https://www.liberalalliance.dk/politik/velfaerd/',
        'https://www.liberalalliance.dk/politik/retspolitik/',
        'https://www.liberalalliance.dk/politik/arbejdsmarked/',
        'https://www.liberalalliance.dk/politik/klima/',
        'https://www.liberalalliance.dk/politik/klima/energi/',
        'https://www.liberalalliance.dk/politik/sundhed/',
        'https://www.liberalalliance.dk/politik/uddannelsespolitik/',
        'https://www.liberalalliance.dk/politik/udenrigspolitik/',
        'https://www.liberalalliance.dk/politik/forsvarspolitik/',
        'https://www.liberalalliance.dk/politik/udlaendingepolitik/',
        'https://www.liberalalliance.dk/politik/eu/',
        'https://www.liberalalliance.dk/politik/transportpolitik/',
        'https://www.liberalalliance.dk/politik/velfaerd/aeldrepolitik/',
        'https://www.liberalalliance.dk/politik/socialpolitik/',
        'https://www.liberalalliance.dk/politik/bolig/',
        'https://www.liberalalliance.dk/politik/ligestilling/',
        'https://www.liberalalliance.dk/politik/offentlig-sektor/',
        'https://www.liberalalliance.dk/politik/miljoe-og-natur/',
        'https://www.liberalalliance.dk/politik/kultur/',
        'https://www.liberalalliance.dk/politik/afgifter/',
        'https://www.liberalalliance.dk/politik/it/',
        'https://www.liberalalliance.dk/politik/arbejdsmarked/ivaerksaettere-og-selvstaendige/',
        'https://www.liberalalliance.dk/politik/arbejdsmarked/udenlandsk-arbejdskraft/',
        'https://www.liberalalliance.dk/politik/erhvervspolitik-2/',
    ],
    'O': [  # Dansk Folkeparti – https://danskfolkeparti.dk/vores-politik/
        'https://danskfolkeparti.dk/maerkesager/nej-til-kraenkelseshysteri/',
        'https://danskfolkeparti.dk/maerkesager/vi-skal-selv-bestemme/',
        'https://danskfolkeparti.dk/maerkesager/dyrevelfaerd/',
        'https://danskfolkeparti.dk/maerkesager/lov-og-orden/',
        'https://danskfolkeparti.dk/maerkesager/vores-seniorer/',
        'https://danskfolkeparti.dk/maerkesager/stop-for-asyl-i-danmark/',
        'https://danskfolkeparti.dk/maerkesager/velfaerd-sundhed/',
        'https://danskfolkeparti.dk/maerkesager/stram-udlaendingepolitik/',
        'https://danskfolkeparti.dk/vores-udspil/danskerne-foerst-ogsaa-i-finanssektoren/',
        'https://danskfolkeparti.dk/vores-udspil/statsborgerskab-dybde-over-bredde/',
        'https://danskfolkeparti.dk/vores-udspil/ro-orden-og-tryghed-i-folkeskolen/',
        'https://danskfolkeparti.dk/vores-udspil/markante-velfaerdsloeft-og-skattelettelser-til-danskerne/',
        'https://danskfolkeparti.dk/vores-udspil/ordentlige-forhold-til-vores-soldater-og-vaernepligtige/',
        'https://danskfolkeparti.dk/vores-udspil/bedre-dyrevelfaerd-i-eu/',
        'https://danskfolkeparti.dk/vores-udspil/skeen-i-den-anden-haand-en-kontant-retspolitik/',
        'https://danskfolkeparti.dk/vores-udspil/10-punktsplan-til-at-genoprette-tilliden-til-politikerne/',
        'https://danskfolkeparti.dk/vores-udspil/dansk-fortid-dansk-fremtid/',
        'https://danskfolkeparti.dk/vores-udspil/handleplan-for-de-blaa-veteraner-vi-skal-passe-paa-dem-der-passer-paa-os/',
        'https://danskfolkeparti.dk/vores-udspil/et-vaerdigt-liv-hele-livet/',
        'https://danskfolkeparti.dk/vores-udspil/mere-naerhed-mindre-papir/',
        'https://danskfolkeparti.dk/holdninger/usa-nato/',
        'https://danskfolkeparti.dk/holdninger/ulandsbistand/',
        'https://danskfolkeparti.dk/holdninger/udenrigspolitik/',
        'https://danskfolkeparti.dk/holdninger/uddannelse/',
        'https://danskfolkeparti.dk/holdninger/transport/',
        'https://danskfolkeparti.dk/holdninger/socialpolitik/',
        'https://danskfolkeparti.dk/holdninger/skat/',
        'https://danskfolkeparti.dk/holdninger/rigsfaellesskabet/',
        'https://danskfolkeparti.dk/holdninger/psykisk-sygdom/',
        'https://danskfolkeparti.dk/holdninger/miljoe-og-landskaber/',
        'https://danskfolkeparti.dk/holdninger/medier/',
        'https://danskfolkeparti.dk/holdninger/ligestilling/',
        'https://danskfolkeparti.dk/holdninger/landdistrikterne/',
        'https://danskfolkeparti.dk/holdninger/landbrug-og-foedevarer/',
        'https://danskfolkeparti.dk/holdninger/kultur/',
        'https://danskfolkeparti.dk/holdninger/klima-og-energi/',
        'https://danskfolkeparti.dk/holdninger/kirken/',
        'https://danskfolkeparti.dk/holdninger/indenrigspolitik/',
        'https://danskfolkeparti.dk/holdninger/idraet/',
        'https://danskfolkeparti.dk/holdninger/handicappolitik/',
        'https://danskfolkeparti.dk/holdninger/forsvar/',
        'https://danskfolkeparti.dk/holdninger/forbrugerpolitik/',
        'https://danskfolkeparti.dk/holdninger/folkeskolen/',
        'https://danskfolkeparti.dk/holdninger/finans/',
        'https://danskfolkeparti.dk/holdninger/familie/',
        'https://danskfolkeparti.dk/holdninger/erhverv/',
        'https://danskfolkeparti.dk/holdninger/energi/',
        'https://danskfolkeparti.dk/holdninger/din-kommune-2/',
        'https://danskfolkeparti.dk/holdninger/det-digitale-danmark/',
        'https://danskfolkeparti.dk/holdninger/bolig/',
        'https://danskfolkeparti.dk/holdninger/beskaeftigelse/',
        'https://danskfolkeparti.dk/holdninger/arbejdsmarkedet/',
    ],
    'M': ['https://moderaterne.dk/moderaterne-mener/'],
    'V': [  # Venstre – https://www.venstre.dk/politik/politik-a-aa
        'https://www.venstre.dk/politik/politik-a-aa/boligskattepolitik',
        'https://www.venstre.dk/politik/politik-a-aa/boligpolitik',
        'https://www.venstre.dk/politik/politik-a-aa/beskaeftigelse',
        'https://www.venstre.dk/politik/politik-a-aa/digitaliseringspolitik',
        'https://www.venstre.dk/politik/politik-a-aa/eu',
        'https://www.venstre.dk/politik/politik-a-aa/erhvervspolitik',
        'https://www.venstre.dk/politik/politik-a-aa/energipolitik',
        'https://www.venstre.dk/politik/politik-a-aa/fodevare-landbrugs-og-fiskeripolitik',
        'https://www.venstre.dk/politik/politik-a-aa/forsvarspolitik',
        'https://www.venstre.dk/politik/politik-a-aa/finanspolitik',
        'https://www.venstre.dk/politik/politik-a-aa/familiepolitik',
        'https://www.venstre.dk/politik/politik-a-aa/ivaerksaetteri',
        'https://www.venstre.dk/politik/politik-a-aa/kvalificeret-arbejdskraft',
        'https://www.venstre.dk/politik/politik-a-aa/kulturpolitik',
        'https://www.venstre.dk/politik/politik-a-aa/klimapolitik',
        'https://www.venstre.dk/politik/politik-a-aa/folkekirke-og-religion',
        'https://www.venstre.dk/politik/politik-a-aa/ligestilling',
        'https://www.venstre.dk/politik/politik-a-aa/landdistrikter-og-oeer',
        'https://www.venstre.dk/politik/politik-a-aa/natur-og-miljopolitik',
        'https://www.venstre.dk/politik/politik-a-aa/offentlig-sektor',
        'https://www.venstre.dk/politik/politik-a-aa/psykiatri',
        'https://www.venstre.dk/politik/politik-a-aa/pensionspolitik',
        'https://www.venstre.dk/politik/politik-a-aa/rigsfaellesskabet',
        'https://www.venstre.dk/politik/politik-a-aa/retspolitik',
        'https://www.venstre.dk/politik/politik-a-aa/sundhedspolitik',
        'https://www.venstre.dk/politik/politik-a-aa/socialpolitik',
        'https://www.venstre.dk/politik/politik-a-aa/skattestop',
        'https://www.venstre.dk/politik/politik-a-aa/skat',
        'https://www.venstre.dk/politik/politik-a-aa/statsborgerskab',
        'https://www.venstre.dk/politik/politik-a-aa/transportpolitik',
        'https://www.venstre.dk/politik/politik-a-aa/undervisnings-og-skolepolitik',
        'https://www.venstre.dk/politik/politik-a-aa/udviklingspolitik',
        'https://www.venstre.dk/politik/politik-a-aa/udlaendingepolitik',
        'https://www.venstre.dk/politik/politik-a-aa/udenrigspolitik',
        'https://www.venstre.dk/politik/politik-a-aa/uddannelsespolitik',
        'https://www.venstre.dk/politik/politik-a-aa/velfaerd',
        'https://www.venstre.dk/politik/politik-a-aa/aeldrepolitik',
    ],
    'Æ': [  # Danmarksdemokraterne – https://danmarksdemokraterne.dk/forside/politik/
        'https://danmarksdemokraterne.dk/forside/politik/et-danmark-i-balance/',
        'https://danmarksdemokraterne.dk/forside/politik/udlaendingepolitik/',
        'https://danmarksdemokraterne.dk/forside/politik/sundhed/',
        'https://danmarksdemokraterne.dk/forside/politik/produktionsdanmark/',
        'https://danmarksdemokraterne.dk/forside/politik/nej-tak-til-co2-afgift/',
        'https://danmarksdemokraterne.dk/forside/politik/nej-til-jernmarker/',
        'https://danmarksdemokraterne.dk/forside/politik/principprogram/',
    ],
    'Ø': [  # Enhedslisten – undersider under politisk-abc (fra hvad-mener-enhedslisten-om SPA)
        'https://enhedslisten.dk/politisk-abc/afgifter-og-moms/',
        'https://enhedslisten.dk/politisk-abc/anbragte-boern-og-unge/',
        'https://enhedslisten.dk/politisk-abc/arbejdsloeshed/',
        'https://enhedslisten.dk/politisk-abc/arbejdspligt/',
        'https://enhedslisten.dk/politisk-abc/arne-pension/',
        'https://enhedslisten.dk/politisk-abc/atomkraft/',
        'https://enhedslisten.dk/politisk-abc/aviser/',
        'https://enhedslisten.dk/politisk-abc/banker/',
        'https://enhedslisten.dk/politisk-abc/biodiversitet/',
        'https://enhedslisten.dk/politisk-abc/bortadoption/',
        'https://enhedslisten.dk/politisk-abc/centralisering/',
        'https://enhedslisten.dk/politisk-abc/cybersikkerhed/',
        'https://enhedslisten.dk/politisk-abc/daginstitutioner/',
        'https://enhedslisten.dk/politisk-abc/dagpenge/',
        'https://enhedslisten.dk/politisk-abc/digitale-kraenkelser/',
        'https://enhedslisten.dk/politisk-abc/digital-medborgerskab/',
        'https://enhedslisten.dk/politisk-abc/drikkevand/',
        'https://enhedslisten.dk/politisk-abc/dyrevelfaerd/',
        'https://enhedslisten.dk/politisk-abc/energi/',
        'https://enhedslisten.dk/politisk-abc/fattigdom/',
        'https://enhedslisten.dk/politisk-abc/fiskeri/',
        'https://enhedslisten.dk/politisk-abc/flygtningepolitik/',
        'https://enhedslisten.dk/politisk-abc/foedevarer/',
        'https://enhedslisten.dk/politisk-abc/folkepension/',
        'https://enhedslisten.dk/politisk-abc/folkeskole/',
        'https://enhedslisten.dk/politisk-abc/forbrug/',
        'https://enhedslisten.dk/politisk-abc/forskning/',
        'https://enhedslisten.dk/politisk-abc/foertidspension/',
        'https://enhedslisten.dk/politisk-abc/fritidstilbud/',
        'https://enhedslisten.dk/politisk-abc/global-retsorden/',
        'https://enhedslisten.dk/politisk-abc/gron-politik/',
        'https://enhedslisten.dk/politisk-abc/hadforbrydelser/',
        'https://enhedslisten.dk/politisk-abc/havmiljoe/',
        'https://enhedslisten.dk/politisk-abc/hjemloeshed/',
        'https://enhedslisten.dk/politisk-abc/indkoebspolitik/',
        'https://enhedslisten.dk/politisk-abc/international-adoption/',
        'https://enhedslisten.dk/politisk-abc/israel-og-palaestina/',
        'https://enhedslisten.dk/politisk-abc/kemikalier/',
        'https://enhedslisten.dk/politisk-abc/klima/',
        'https://enhedslisten.dk/politisk-abc/kontanthjaelp/',
        'https://enhedslisten.dk/politisk-abc/kraenkelser/',
        'https://enhedslisten.dk/politisk-abc/kriminalitet/',
        'https://enhedslisten.dk/politisk-abc/kritisk-infrastruktur/',
        'https://enhedslisten.dk/politisk-abc/kvoteflygtninge/',
        'https://enhedslisten.dk/politisk-abc/landbrug/',
        'https://enhedslisten.dk/politisk-abc/menneskerettigheder/',
        'https://enhedslisten.dk/politisk-abc/miljoe/',
        'https://enhedslisten.dk/politisk-abc/mistrivsel/',
        'https://enhedslisten.dk/politisk-abc/negativ-social-kontrol/',
        'https://enhedslisten.dk/politisk-abc/partnervold/',
        'https://enhedslisten.dk/politisk-abc/pension/',
        'https://enhedslisten.dk/politisk-abc/permanent-opholdstilladelse/',
        'https://enhedslisten.dk/politisk-abc/profitfri-socialomraade/',
        'https://enhedslisten.dk/politisk-abc/retspolitik/',
        'https://enhedslisten.dk/politisk-abc/samtykke/',
        'https://enhedslisten.dk/politisk-abc/selvstaendige/',
        'https://enhedslisten.dk/politisk-abc/seniorpension/',
        'https://enhedslisten.dk/politisk-abc/sikkerhed/',
        'https://enhedslisten.dk/politisk-abc/skattelettelser/',
        'https://enhedslisten.dk/politisk-abc/skattepolitik/',
        'https://enhedslisten.dk/politisk-abc/skov/',
        'https://enhedslisten.dk/politisk-abc/statsborgerskab/',
        'https://enhedslisten.dk/politisk-abc/su/',
        'https://enhedslisten.dk/politisk-abc/surrogasi/',
        'https://enhedslisten.dk/politisk-abc/sygedagpenge/',
        'https://enhedslisten.dk/politisk-abc/tidlig-indsats/',
        'https://enhedslisten.dk/politisk-abc/tilbagetraekning/',
        'https://enhedslisten.dk/politisk-abc/tilskud/',
        'https://enhedslisten.dk/politisk-abc/transport/',
        'https://enhedslisten.dk/politisk-abc/udenrigspolitik/',
        'https://enhedslisten.dk/politisk-abc/uddannelsespolitik/',
        'https://enhedslisten.dk/politisk-abc/velfaerd/',
        'https://enhedslisten.dk/politisk-abc/aeldrepolitik/',
    ],
    'Å': [  # Alternativet – https://www.alternativet.dk/politik
        'https://www.alternativet.dk/politik/klima',
        'https://www.alternativet.dk/politik/miljoe',
        'https://www.alternativet.dk/politik/natur-og-biodiversitet',
        'https://www.alternativet.dk/politik/sundhed',
        'https://www.alternativet.dk/politik/boern-og-familier',
        'https://www.alternativet.dk/politik/asyl-og-integration',
        'https://www.alternativet.dk/politik/dyrevelfaerd',
        'https://www.alternativet.dk/politik/beskaeftigelse-og-ivaerksaetteri',
        'https://www.alternativet.dk/politik/ny-oekonomi',
        'https://www.alternativet.dk/politik/ligestilling-og-mangfoldighed',
        'https://www.alternativet.dk/politik/transport',
        'https://www.alternativet.dk/politik/landbrug',
        'https://www.alternativet.dk/politik/eu-politik',
        'https://www.alternativet.dk/politik/global-politik',
        'https://www.alternativet.dk/politik/handicap',
        'https://www.alternativet.dk/politik/psykiatri',
        'https://www.alternativet.dk/politik/retspolitik',
        'https://www.alternativet.dk/politik/kunst-og-kultur',
        'https://www.alternativet.dk/politik/aeldre',
        'https://www.alternativet.dk/politik/digital-baeredygtighed-og-it',
        'https://www.alternativet.dk/politik/demokrati',
        'https://www.alternativet.dk/politik/mere-fri-tid',
        'https://www.alternativet.dk/politik/socialpolitik',
        'https://www.alternativet.dk/politik/skole-og-uddannelse',
        'https://www.alternativet.dk/politik/tro-og-livssyn',
        'https://www.alternativet.dk/politik/pension',
        'https://www.alternativet.dk/politik/forsvar',
    ],
}

# Weaviate collection names must be ASCII; map Danish party letters.
WEAVIATE_PARTY_LETTER = {'Å': 'AA', 'Æ': 'AE', 'Ø': 'OE'}


def weaviate_collection_name(party_id: str) -> str:
    """Return Weaviate-safe collection name for a party (Å→AA, Æ→AE, Ø→OE)."""
    return WEAVIATE_PARTY_LETTER.get(party_id, party_id)


PARTY_NAMES = {
    'A': 'Socialdemokratiet',
    'B': 'Radikale Venstre',
    'C': 'Det Konservative Folkeparti',
    'F': 'SF - Socialistisk Folkeparti',
    'H': 'Borgernes Parti - Lars Boje Mathiesen',
    'I': 'Liberal Alliance',
    'M': 'Moderaterne',
    'O': 'Dansk Folkeparti',
    'V': 'Venstre, Danmarks Liberale Parti',
    'Æ': 'Danmarksdemokraterne - Inger Støjberg',
    'Ø': 'Enhedslisten - De Rød-Grønne',
    'Å': 'Alternativet',
}